# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
$:.unshift("~/.rubymotion/rubymotion-templates")

platform = ENV.fetch('platform', 'osx')

require "motion/project/template/#{platform}"
require 'rubygems'

begin
  require 'bundler'
  ARGV.join(' ') =~ /spec/ ? Bundler.require(:default, :spec) : Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  app.name        = 'motion-markdown-it-plugins'
  app.identifier  = 'com.motion-gemtest.motion-markdown-it-plugins'
end
